repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Format Rust code
        entry: cargo fmt
        language: system
        args: [--check]
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check Rust code
        entry: cargo check
        language: system
        args: [--all-targets, --all-features]
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code
        entry: cargo clippy
        language: system
        args: [-- -D warnings]
        files: \.rs$
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        files: ^python/.*\.py$|^tests/python/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [--fix]
        files: ^python/.*\.py$|^tests/python/.*\.py$
        types_or: [python]
      - id: ruff-format
        files: ^python/.*\.py$|^tests/python/.*\.py$
        types_or: [python]
