//! Build script for spreadsheet integration
//!
//! Handles platform-specific build requirements for Excel COM add-in and Google Apps Script.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    
    let target = env::var("TARGET").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    
    if target.contains("windows") {
        println!("cargo:rerun-if-changed=src/spreadsheet/excel_addin.rs");
        println!("cargo:rerun-if-changed=Cargo.toml");
        
        // Create Windows-specific output directory
        let windows_out = Path::new(&out_dir).join("windows");
        fs::create_dir_all(&windows_out).unwrap();
        
        // Generate Windows-specific bindings
        generate_windows_bindings(&windows_out);
        
        // Copy Windows resources
        copy_windows_resources(&windows_out);
        
        println!("cargo:warning=Excel COM add-in will be built for Windows target");
    } else {
        println!("cargo:warning=Excel COM add-in is Windows-only, skipping for target: {}", target);
    }
}

/// Generate Windows COM bindings
fn generate_windows_bindings(out_dir: &Path) {
    // This would typically use windows-rs to generate bindings
    // For now, we'll create a placeholder file
    let bindings_file = out_dir.join("excel_bindings.rs");
    
    let bindings_content = r#"// Generated Windows COM bindings for Excel
// This file is auto-generated by build.rs

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use std::ptr;

// Excel COM interface constants
pub const CLSID_ExcelApplication: &str = "{00024500-0000-0000-C000-000000000046}";
pub const CLSID_ExcelWorkbook: &str = "{00020819-0000-0000-C000-000000000046}";
pub const CLSID_ExcelWorksheet: &str = "{00020820-0000-0000-C000-000000000046}";

// Excel COM interface types
#[repr(C)]
pub struct ExcelVariant {
    pub vt: u16,
    pub w_reserved1: u16,
    pub w_reserved2: u16,
    pub w_reserved3: u16,
    pub union_field: [u8; 8],
}

// Excel COM interface functions
extern "system" {
    pub fn CoInitializeEx(pv_reserved: *mut std::ffi::c_void, dw_co_init: u32) -> i32;
    pub fn CoUninitialize() -> i32;
    pub fn CoCreateInstance(rclsid: *const std::ffi::c_void, p_outer: *mut std::ffi::c_void, dw_cls_context: u32, riid: *const std::ffi::c_void, ppv: *mut *mut std::ffi::c_void) -> i32;
}

// Excel add-in entry points
#[no_mangle]
pub extern "stdcall" fn DllMain(hinst: *mut std::ffi::c_void, reason: u32, reserved: *mut std::ffi::c_void) -> i32 {
    match reason {
        1 => { // DLL_PROCESS_ATTACH
            println!("Excel add-in loaded");
        }
        0 => { // DLL_PROCESS_DETACH
            println!("Excel add-in unloaded");
        }
        _ => {}
    }
    1
}
"#;
    
    fs::write(&bindings_file, bindings_content).unwrap();
    println!("cargo:warning=Generated Windows bindings at {:?}", bindings_file);
}

/// Copy Windows-specific resources
fn copy_windows_resources(out_dir: &Path) {
    // Create resources directory
    let resources_dir = out_dir.join("resources");
    fs::create_dir_all(&resources_dir).unwrap();
    
    // Create manifest file for Excel add-in
    let manifest_content = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity
    type="win32"
    name="Vectrill.Excel.Addin"
    version="1.0.0.0"
    processorArchitecture="x86"
  />
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Office.Interop.Excel"
        version="15.0.0.0"
        processorArchitecture="x86"
        publicKeyToken="71e9bce111e9429c"
        language="neutral"
      />
    </dependentAssembly>
  </dependency>
</assembly>"#;
    
    let manifest_file = resources_dir.join("Vectrill.Excel.Addin.manifest");
    fs::write(&manifest_file, manifest_content).unwrap();
    
    // Create registry script
    let registry_script = r#"@echo off
echo Registering Vectrill Excel Add-in...

REM Register the add-in with Excel
regsvr32.exe /s "%~dp0Vectrill.Excel.Addin.dll"

echo Vectrill Excel Add-in registration complete.
pause
"#;
    
    let script_file = resources_dir.join("register.bat");
    fs::write(&script_file, registry_script).unwrap();
    
    // Create uninstall script
    let uninstall_script = r#"@echo off
echo Unregistering Vectrill Excel Add-in...

regsvr32.exe /u /s "%~dp0Vectrill.Excel.Addin.dll"

echo Vectrill Excel Add-in unregistration complete.
pause
"#;
    
    let uninstall_file = resources_dir.join("unregister.bat");
    fs::write(&uninstall_file, uninstall_script).unwrap();
    
    println!("cargo:warning=Copied Windows resources to {:?}", resources_dir);
}
